#!/bin/bash
set -euo pipefail
# make a personalized terraform tree, to avoid clashing of state / locking
# during testing:

export PATH=/bin:/usr/bin

src='terraform/env'
dst="$src.$USER"

set -x
: clear out the destination
git rm -rf "$dst" || true
rm -rf "$dst"

: clean and copy the source
git clean "$src" -fdxf
cp -r "$src" "$dst"

git add "$dst"
set +x

echo "Done. Please commit: $dst"
