#!/bin/bash
set -euo pipefail

HERE="$(cd "$(dirname "$0")"; pwd)"

lock_id=$("$HERE/"../tf-lock/tf-lock "$@")
status=$?

lock_obtained="false"
if [ $status -eq 0 ]; then
  lock_obtained="true"
fi

echo "{\"lock_id\": \"$lock_id\", \"lock_obtained\": $lock_obtained}"

if [ $status -ne 0 ]; then
  exit 1
fi
