#!/bin/bash
set -euo pipefail

HERE="$(cd "$(dirname "$0")"; pwd)"

echo -n lock_id=
"$HERE/"../tf-lock/tf-lock "$@"
status=$?

if [ $status -eq 0 ]; then
  echo "true"
else
  echo "false"
  exit 1
fi
