#!/bin/bash

summary=""

echo ls -l

for file in etc/usr/artifacts/lock_result_*/lock_result.txt; do
  lock_result=$(cat "$file")

  # Extract the artifact name, removing the prefix "lock_result_" and replacing '-' with '/'
  artifact_name=$(echo "$file" | sed -e 's/^lock_result_//' -e 's/-/\//g')

  summary+="$artifact_name: $lock_result"$'\n'
done

echo -e "$summary"