#!/bin/bash

summary=""

for file in lock_result_*/lock_result.txt; do

  lock_result=$(cat "$file")

  # Extract the artifact name, removing the prefix "lock_result_" and replacing '-' with '/'
  artifact_name=$(echo "$file" | sed -e 's/^lock_result_//' -e 's/-/\//g')

  # Add a locked emoji if the artifact is locked
  if [[ "$lock_result" == "true" ]]; then
    lock_result="✅🔒"
  else
    lock_result="❌"
  fi
  summary+="$artifact_name: $lock_result,"
done

echo "lock_summary=$summary" >> "$GITHUB_OUTPUT"