#!/bin/bash
set -euxo pipefail
HERE="$(cd "$(dirname "$0")"; pwd)"

found() {
  service_account="$1"
  echo "terraformer=$service_account" >> "$GITHUB_OUTPUT"
  exit 0
}

if config="$("$HERE/"nearest-config-file sudo-gcp.toml)"; then
  found "$(toml get sudo-gcp.toml service_account --raw)"
fi

# DELETEME: support for legacy codebases
if config="$("$HERE/"nearest-config-file sac-terraformer)"; then
  found "$(cat "$config")"
fi


cat >&2 <<EOF
Unable to find the correct service account for your terraform.
Please add a sudo-gcp.toml file to your project.

https://github.com/getsentry/sudo-gcp
EOF
exit 1
