# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "gcs" {
    bucket   = "sac-dev-tf--tacos-gha"
    prefix   = "tacos-demo/spec/behaviors/terragrunt_source_slice.env/module/slice-2-vm"
  }
}
