#!/bin/bash
set -eEuo pipefail
HERE="$(cd "$(dirname "$0")"; pwd)"
export PATH="$HERE/lib:$PATH"
root_module="${1:-"$PWD"}"

if [[ "${DEBUG:-}" ]]; then
  set -x
fi

cd "$root_module"
fancy_error="$(
  # swap stdout and stderr:
  terraform force-unlock -force -- -1 3>&2 2>&1 1>&3 <<< ""
)" && status=$? || status=$?

# strip ansi fanciness from error messages, for automated consumption
error="$(
  uncolor <<< "$fancy_error" |
  sed -r 's/^│ //'
)"


if grep -Eq <<< "$error" $'ID:'; then
  "$HERE/"lib/error2json <<< "$error"
elif grep -Eq <<< "$error" \
    $'^\t\* storage: object doesn'\''t exist$' \
; then
  echo '{"lock": false}'
elif grep -Eq <<< "$error" \
  'Error: .*Backend initialization required, please run "terraform init"' \
; then
  terraform init >&2
  exec "$0" "$@"
else
  cat >&2 <<< "$fancy_error"
  exit "$status"
fi
