#!/bin/bash
set -eEuo pipefail
root_module="${1:-"$PWD"}"

error2json() {
  printf '{'
  sed -rn '
    1,/^Lock Info:$/ d
    /^  /! {
      x
      s/\n//g
      p
      q
    }
    s/^  /"/
    s/: +/": "/
    s/$/",/
    H
  ' | tr -d '\n'
  echo '"lock":true}'
}


cd "$root_module"
###terraform init 2>/dev/null
error="$(
  # swap stdout and stderr:
  terraform force-unlock -force 1 3>&2 2>&1 1>&3 <&-
)" && status=$? || status=$?


if (( status == 0 )); then
  echo >&2 This should be impossible...
  exit 1
fi

# print the first value labelled "ID:"
if grep <<< "$error" -q ID:; then
  error2json <<< "$error"
elif grep -q <<< "$error" -m1 'Failed to unlock state:'; then
  echo '{"lock": false}'
elif grep -q <<< "$error" 'Error: .*Backend initialization required, please run "terraform init"'; then
  terraform init >&2
  exec "$0" "$@"
else
  cat >&2 <<< "$error"
  exit "$status"
fi
