#!/bin/bash
set -eo pipefail
HERE="$(cd "$(dirname "$0")"; pwd)"

lock_id=$("$HERE/"tf-lock-id) && status=$? || status=$?

if (( status == 0 )); then
  terraform force-unlock -force -- "$lock_id" >&2
elif (( status == 2 )); then
  echo >&2 "(terraform state not locked)"
  exit 0
else
  # surface any unexpected errors
  cat >&2 <<< "$lock_id"
  exit "$status"
fi
