#!/bin/bash
set -euo pipefail
HERE="$(cd "$(dirname "$0")"; pwd)"
root_module="${1:-"$PWD"}"

set -x
cd "$root_module"
lock_id=$("$HERE/"tf-lock-id) && status=$? || status=$?

if (( status == 2 )); then
  terraform init
  "$HERE/"lib/tf-lock-acquire.exp  # acquire
  # second acquire should fail, and print the lock id
  if "$HERE/"lib/tf-lock-acquire.exp; then
    echo >&2 lock not obtained!
    exit 1
  fi
elif (( status == 0 )); then
  # already done!
  cat <<< "$lock_id"
  exit 0
else
  # surface any unexpected errors
  cat >&2 <<< "$lock_id"
  exit "$status"
fi
