name: Terraform Apply on Command

on:
  pull_request:
    types: [labeled]
  pull_request_target:
    types: [closed]

jobs:
  apply:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    if: ${{ github.event.label.name == ':taco::apply' }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Checkout our scripts
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Obtain the lock
        id: lock_check
        run: ./bin/obtain-lock

      - name: Terraform Apply
        id: apply
        run: ./bin/tf-apply
      
      - name: Reset label
        uses: actions/github-script@v7
        if: always()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: ':taco::apply'
            })
