name: Terraform Apply on Command

on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [closed]

jobs:
  apply:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    if:
      github.event.issue.pull_request != null &&
      contains(github.event.comment.body, '/terraform apply') &&
      github.event.comment.user.type != 'Bot'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: refs/pull/${{ github.event.issue.number }}/merge

      - name: Checkout our scripts
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Obtain the lock
        id: lock_check
        run: ./bin/obtain-lock

      - name: Terraform Apply
        id: apply
        run: ./bin/tf-apply
