name: Required check

on:
  pull_request:

jobs:
  tacos-gha:
    uses: getsentry/tacos-gha/.github/workflows/required_check.yml@maxwelllwang/wait-for-required-check
    with:
      tacos_gha_ref: refs/heads/maxwelllwang/wait-for-required-check
