name: Required check

on:
  pull_request:

jobs:
  required_check:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Perform check
        run: |
          pwd
          ls
