name: Required check

on:
  pull_request: null

jobs:
  required_check:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Perform check
        run: |
          if [ -e required_check.fail ]; then exit 1; fi
