name: Scratch

on:
  workflow_dispatch:
  pull_request:

defaults:
  run:
    shell: bash -euxo pipefail {0}

jobs:
  scratch:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - id: summary
        run: |
          echo summary='"oh\nhi"' >> "$GITHUB_OUTPUT"

      - name: Comment on PR regarding lock state
        uses: actions/github-script@v7
        env:
          summary: ${{steps.summary.outputs.summary}}
        with:
          script: |
            // console.log(this)
            // console.log(global)

            console.log("Environ:")
            console.log(process.env)
            console.log("---\n")

            console.log("Summary:")
            console.log(process.env.summary)
            console.log("---\n")

            console.log("Arguments:\n  ")
            console.log(arguments)
            const globals = Object.getOwnPropertyNames(this)
            globals.sort()
            console.log("---\n")

            console.log("Globals:\n  ")
            console.log(globals.join("\n  "))
            console.log("---\n")

            // console.log(global.context)
