name: Scratch

on:
  workflow_dispatch:
  pull_request:

defaults:
  run:
    shell: bash -euxo pipefail {0}

jobs:
  scratch:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - id: summary
        run: |
          echo summary='"oh\nhi"' >> "$GITHUB_OUTPUT"

      - name: Comment on PR regarding lock state
        uses: actions/github-script@v7
        with:
          script: |
            console.log(context)
            console.log(needs)
            console.log(steps)
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "Terraform lock state:\n\n\`\`\`\n" + ${{ steps.summary.outputs.summary }} + "\n\`\`\`"
            });
