name: Scratch

on:
  workflow_dispatch: null
  pull_request:
    types: [synchronize]

jobs:
  tacos-gha:
    uses: getsentry/tacos-gha/.github/workflows/scratch.yml@test/fix_reset_label
    with:
      tacos_gha_ref: refs/heads/test/fix_reset_label
