on:
  workflow_dispatch: null
  pull_request:
    paths:
      - "**/scratch-matrix.yml"

defaults:
  run:
    shell: bash -euxo pipefail {0}

jobs:
  input-data1:
    runs-on: ubuntu-latest
    outputs:
      input-data4: ${{ toJSON(steps.input-data2.outputs) }}
    steps:
      - name: input-data2
        run: |
          printf "input-data3=" >> "$GITHUB_OUTPUT"
          seq 5 | jq -R | jq -cs >> "$GITHUB_OUTPUT"

  show-needs:
    runs-on: ubuntu-latest
    needs:
      - input-data1
    steps:
      - run: |
          set +x; cat <<'EOF'
            ${{ toJSON(needs) }}
          EOF

  matrix-processing:
    runs-on: ubuntu-latest
    needs:
      - input-data1
    strategy:
      matrix:
        data: ${{ needs }}

    steps:
      - run: |
          : Processing...
          echo ${{matrix.data}}
          printf "x%s=%s" "$RANDOM" "$RANDOM" >> "$GITHUB_OUTPUT"
