on:
  workflow_dispatch: null
  pull_request:
    paths:
      - "**/scratch-matrix.yml"

defaults:
  run:
    shell: bash -euxo pipefail {0}

jobs:
  input-data1:
    runs-on: ubuntu-latest
    outputs:
      steps: ${{ toJSON(steps) }}
    steps:
      - id: input-data2
        run: |
          printf "input-data3=" >> "$GITHUB_OUTPUT"
          seq 5 | jq -R | jq -cs >> "$GITHUB_OUTPUT"

  show-inputs:
    runs-on: ubuntu-latest
    needs:
      - input-data1
    steps:
      - run: |
          set +x; cat >>"$GITHUB_STEP_SUMMARY" <<'EOF'
          ```
          needs:
            ${{ toJSON(needs) }}

          needs.input-data1.outputs.steps:
            ${{ needs.input-data1.outputs.steps }}

          needs.input-data1.outputs.steps.input-data2.outputs.input-data3:
            ${{ fromJSON(needs.input-data1.outputs.steps).input-data2.outputs.input-data3 }}
          ```
          EOF

  matrix-processing:
    runs-on: ubuntu-latest
    needs:
      - input-data1
    outputs:
      steps: ${{ toJSON(steps) }}
    strategy:
      matrix:
        data: |
          ${{
            fromJSON(
              fromJSON(
                needs
                .input-data1
                .outputs
                .steps
              )
              .input-data2
              .outputs
              .input-data3
            )
          }}

    steps:
      - run: |
          : Processing...
          echo ${{matrix.data}}
          printf "x%s=%s" "$RANDOM" "$RANDOM" >> "$GITHUB_OUTPUT"

  show-ouputs:
    runs-on: ubuntu-latest
    needs:
      - matrix-processing
    steps:
      - run: |
          set +x; cat >>"$GITHUB_STEP_SUMMARY" <<'EOF'
          ```
          needs:
            ${{ toJSON(needs) }}

          needs.matrix-processing.outputs.steps:
            ${{ needs.matrix-processing.outputs.steps }}
          ```
          EOF
