name: Scratch

on:
  workflow_call:
    inputs:
      working_dir:
        default: "CALL:."
        type: "string"

      # NOTE: Please keep these in sync with ../../.terra*-version files.
      tf_version:
        default: "CALL:1.6.4"
        type: "string"
      tg_version:
        default: "CALL:0.53.5"
        type: "string"
  workflow_dispatch:
    inputs:
      working_dir: { default: "DISPATCH:." }

      # NOTE: Please keep these in sync with ../../.terra*-version files.
      tf_version: { default: "DISPATCH:1.6.4" }
      tg_version: { default: "DISPATCH:0.53.5" }

  schedule:
    - cron: "0 0 * * *"

  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - closed

defaults:
  run:
    # the default default is:
    #      bash --noprofile --norc -eo pipefail {0}
    shell: bash --noprofile --norc -eo pipefail -ux {0}

env:
  working_dir: "ENV:./terraform/env"
  tf_version: "ENV:1.6.4"
  tg_version: "ENV:0.53.5"

  # fancy-looking xtrace
  PS4: "+ \e[34;1m$\e[m "

jobs:
  scratch:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: ok
        id: ok
        run: echo ok

      - name: show env
        run: |
          sort -z /proc/self/environ |
           tr '\0' '\n'

      - name: show full context
        run: |
          : <<'EOF'
          github:   ${{ toJSON(github) }},
          env:      ${{ toJSON(env) }},
          vars:     ${{ toJSON(vars) }},
          job:      ${{ toJSON(job) }},
          jobs:     # for reusable workflows only
          steps:    ${{ toJSON(steps) }},
          runner:   ${{ toJSON(runner) }},
          secrets:  ${{ toJSON(secrets) }},
          strategy: ${{ toJSON(strategy) }},
          matrix:   ${{ toJSON(matrix) }},
          needs:    ${{ toJSON(needs) }},
          inputs:   ${{ toJSON(inputs) }},
          EOF
