name: Scratch

on:
  workflow_dispatch: null
  pull_request:
    types: [synchronize]

jobs:
  scratch:
    uses: getsentry/tacos-gha/.github/workflows/scratch.yml@bukzor/import-workflows
    with:
      #tacos_gha_ref: refs/heads/stable
      tacos_gha_ref: refs/heads/bukzor/import-workflows
