name: Scratch

on:
  workflow_dispatch: null
  pull_request:
    types: [synchronize]

jobs:
  tacos-gha:
    uses: getsentry/tacos-gha/.github/workflows/scratch.yml@iw/force-unlock-happy
    with:
      tacos_gha_ref: refs/heads/iw/force-unlock-happy
