name: Scratch

on:
  workflow_dispatch: null
  pull_request:
    types: [synchronize]

jobs:
  scratch:
    uses: getsentry/tacos-gha/.github/workflows/scratch.yml@main
    with:
      tacos_gha_ref: refs/heads/main
