name: Scratch

on:
  workflow_dispatch:
  pull_request:

defaults:
  run:
    shell: bash -euxo pipefail {0}

jobs:
  scratch:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - id: summary
        run: |
          echo summary='"oh\nhi"' >> "$GITHUB_OUTPUT"

      - name: Comment on PR regarding lock state
        uses: actions/github-script@v7
        with:
          script: |
            // console.log(context)
            // console.log(this)
            // console.log(global)
            console.log(Object.getOwnPropertyNames(this))
            const globals = Object.getOwnPropertyNames(this)
            globals.sort()
            console.log(globals.join("\n"))
            console.log(global.context)
