name: Scratch

on:
  workflow_dispatch: null
  pull_request:
    types:
      - labeled

jobs:
  tacos-gha:
    uses: getsentry/tacos-gha/.github/workflows/scratch.yml@fix-unlock-all-touched-files
    with:
      tacos_gha_ref: refs/heads/fix-unlock-all-touched-files
