name: Scratch

on:
  workflow_dispatch: null
  pull_request:
    types: [synchronize]

jobs:
  tacos-gha:
    uses: getsentry/tacos-gha/.github/workflows/scratch.yml@bukzor/apply-update-PR
    with:
      tacos_gha_ref: refs/heads/bukzor/apply-update-PR
