name: Scratch

on:
  workflow_dispatch: null
  pull_request:
    types: [synchronize]

jobs:
  tacos-gha:
    uses: getsentry/tacos-gha/.github/workflows/scratch.yml@emarks/lock-and-plan-on-ready
    with:
      tacos_gha_ref: refs/heads/emarks/lock-and-plan-on-ready
