name: Scratch

on:
  workflow_dispatch: null
  pull_request:
    types: [synchronize]

jobs:
  tacos-gha:
    uses: getsentry/tacos-gha/.github/workflows/scratch.yml@fix/unlock_action
    with:
      tacos_gha_ref: refs/heads/fix/unlock_action
