name: Scratch

on:
  workflow_dispatch: null
  pull_request:
    types:
      - labeled

jobs:
  tacos-gha:
    uses: getsentry/tacos-gha/.github/workflows/scratch.yml@emarks/reliable-unlock
    with:
      tacos_gha_ref: refs/heads/emarks/reliable-unlock
