name: Terraform Detect Drift

on:
  workflow_dispatch: null
  schedule:
    - cron: "0 0 * * *"

jobs:
  tacos-gha:
    uses: getsentry/tacos-gha/.github/workflows/tacos_detect_drift.yml@iw/single-lock-comment
    with:
      tacos_gha_ref: refs/heads/iw/single-lock-comment
