name: Terraform Apply

# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
# https://docs.github.com/en/webhooks/webhook-events-and-payloads
on:
  pull_request:
    types: [opened, edited, synchronize, labeled] # need to filter for :tacos::apply label

jobs:
  check_terraform:
    runs-on: ubuntu-latest
    outputs:
      tf_changed: ${{ steps.terraform_changed.outputs.tf_changed }}
    steps:
      - name: Checkout our scripts
        uses: actions/checkout@v3
      - name: Check if the terraform directory has changed
        id: terraform_changed
        run: |
          if git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep -q '^terraform/'; then
            echo "tf_changed=true" >> "$GITHUB_OUTPUT"
          else
            echo "tf_changed=false" >> "$GITHUB_OUTPUT"
          fi
  check_label:
    needs: [check_terraform]
    runs-on: ubuntu-latest
    if: needs.check_terraform.outputs.tf_changed == 'true' && github.event.label.name == ':taco::apply' && github.event.pull_request.draft == 'false'
    steps:
      - name: Prevent premature apply/merging
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            if [[ "${{ github.event.label.name }}" != ":taco::apply" ]] || [[ "${{ github.event.pull_request.draft }}" == "true" ]]; then
              echo "Failing job because label is not :taco::apply or PR is a draft"
              exit 1
            fi
  terraform_apply:
    needs: [check_terraform, check_label]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    if: needs.check_terraform.outputs.tf_changed == 'true'
    steps:
      ## https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
      - name: show event
        run: |
          : <<'EOF'
            ${{toJSON(github.event)}}
          EOF

      - name: Checkout our scripts
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Obtain the lock
        run: ./bin/obtain-lock

      # No need to write a comment on the PR since the user can see the output of the action
      - name: Terraform Apply
        run: ./bin/tf-apply
  reset_label:
    runs-on: ubuntu-latest
    if: github.event.label.name == ':taco::apply'
    steps:
      - name: Reset label
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: ':taco::apply'
            })
