name: Terraform Detect Drift

on:
  workflow_dispatch: null
  schedule:
    - cron: "0 0 * * *"

jobs:
  tacos-gha:
    uses: getsentry/tacos-gha/.github/workflows/tacos_detect_drift.yml@emarks/lock-and-plan-on-ready
    with:
      tacos_gha_ref: refs/heads/emarks/lock-and-plan-on-ready
