name: Terraform Detect Drift

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

env:
  # NOTE: please keep these in sync with ../../.terra*-version
  tf_version: "1.6.4"
  tg_version: "0.53.5"
  working_dir: "."

  # TODO: use action/direnv to keep this centralized and in sync with manual
  # behavior
  TF_CLI_ARGS_plan: "-lock=false -out=plan"

# Cancel in progress workflows on pull_requests.
# https://docs.github.com/en/actions/using-jobs/using-concurrency#example-using-a-fallback-value
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  terraform_detect_drift:
    runs-on: ubuntu-latest
    steps:
      - name: show event
        run: |
          : <<'EOF'
            ${{toJSON(github.event)}}
          EOF

      - name: Checkout
        uses: actions/checkout@v3

      # We don't want to run this job if someone has already obtained the lock
      - name: Obtain the lock
        id: obtain_lock
        run: ./bin/obtain-lock >> $GITHUB_OUTPUT || true

      - name: Plan
        if: steps.obtain_lock.output.lock_obtained == 'true'
        uses: gruntwork-io/terragrunt-action@v2
        continue-on-error: true
        id: plan
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: ${{ env.working_dir }}
          tg_command: "run-all plan -detailed-exitcode"
          tg_comment: true

      - name: Update .drift
        if: steps.plan.outcome == 'failure'
        run: date -Ins > .drift

      - name: Create PR
        if: steps.plan.outcome == 'failure'
        uses: peter-evans/create-pull-request@v5
        with:
          branch: "tacos/drift"
          commit-message: "fix(drift): terraform drift autodetected!"
          body: |
            Drift detected!

            ---

            ```
            {steps.plan.tg_action_output}
            ```
          reviewers: |
            buck.evan@sentry.io
            ian.woodard@sentry.io
          labels: ":taco::drift"
