name: Terraform Apply

# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
# https://docs.github.com/en/webhooks/webhook-events-and-payloads
on:
  pull_request:
    types: [labeled] # need to filter for :tacos::apply label

env:
  # NOTE: please keep these in sync with ../../.terra*-version
  tf_version: "1.6.4"
  tg_version: "0.53.5"
  working_dir: "."
  deploy_environ: "dev"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # TODO: use action/direnv to keep these centralized and in sync with manual
  # behavior
  TERRAGRUNT_INCLUDE_MODULE_PREFIX: true
  TF_CLI_ARGS_plan: "-lock=false -out=plan"

jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    if: |
      github.event.label.name == ':taco::apply' && github.event.pull_request.draft == false
    steps:
      ## https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
      - name: show event
        run: |
          : <<'EOF'
            ${{toJSON(github.event)}}
          EOF

      - name: Checkout our scripts
        uses: actions/checkout@v3

      - name: set workload identity provider
        id: set-workload-identity-provider
        run: ./lib/ci/set-workload-identity-provider "$deploy_environ"

      - name: set terraformer
        id: set-terraformer
        working-directory: ${{ env.working_dir }}
        run: ./lib/ci/set-terraformer

      - name: gcp auth
        id: auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{steps.set-workload-identity-provider.outputs.workload_identity_provider}}
          service_account: ${{steps.set-terraformer.outputs.terraformer}}

      - name: Obtain the lock
        run: ./lib/ci/obtain-lock

      - name: Apply
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: ${{ env.working_dir }}
          tg_command: "run-all apply --auto-approve"
          tg_comment: 1

  reset_label:
    runs-on: ubuntu-latest
    steps:
      - name: Reset label
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: ':taco::apply'
            })
