name: Terraform Apply

on:
  workflow_dispatch: null
  pull_request:
    types: [labeled] # need to filter for :tacos::apply label

jobs:
  terraform_apply:
    uses: getsentry/tacos-gha/.github/workflows/tacos_apply.yml@bukzor/import-workflows
    with:
      #tacos_gha_ref: refs/heads/stable
      tacos_gha_ref: refs/heads/bukzor/import-workflows
