name: Terraform Lock (shared workflow)

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  tacos_lock:
    permissions:
      contents: read
      id-token: write
      pull-requests: write

    uses: getsentry/tacos-gha/.github/workflows/lock@main
    with:
      slices:
        - terragrunt/regions/multi-tenant/tacos-gha
        - terraform/.../dns

      target: "./iac-security/env/prod/"
      gcp_environ: prod
      gha_deploy_environment: iac-security@prod
      service_account_email: iac-security-tf-apply@sac-prod-sa.iam.gserviceaccount.com
    secrets: inherit
    steps:
      - name: show event
        run: |
          : <<'EOF'
            ${{toJSON(github.event)}}
          EOF
