name: Terraform Apply

# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
# https://docs.github.com/en/webhooks/webhook-events-and-payloads
on:
  pull_request:
    types: [labeled] # need to filter for :tacos::apply label

jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      if: |
        github.event.label.name == ':taco::apply'
    steps:
      ## https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
      - name: show event
        run: |
          : '${{toJSON(github.event)}}'

      - name: Checkout our scripts
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Obtain the lock
        run: ./bin/obtain-lock

      # No need to write a comment on the PR since the user can see the output of the action
      - name: Terraform Apply
        run: ./bin/tf-apply

      - name: Reset label
        uses: actions/github-script@v7
        if: always()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: ':taco::apply'
            })
