name: Terraform Apply

on:
  workflow_dispatch: null
  pull_request:
    types:
      - labeled

jobs:
  tacos-gha:
    uses: getsentry/tacos-gha/.github/workflows/tacos_apply.yml@bukzor/matrix-again
    with:
      tacos_gha_ref: refs/heads/bukzor/matrix-again
