name: Terraform Detect Drift

on:
  workflow_dispatch: null
  schedule:
    - cron: "0 0 * * *"

jobs:
  terraform_detect_drift:
    uses: getsentry/tacos-gha/.github/workflows/tacos_detect_drift.yml@bukzor/import-workflows
    with:
      #tacos_gha_ref: refs/heads/stable
      tacos_gha_ref: refs/heads/bukzor/import-workflows
