name: Terraform Apply

on:
  workflow_dispatch: null
  pull_request:
    types:
      - labeled

jobs:
  tacos-gha:
    uses: getsentry/tacos-gha/.github/workflows/tacos_apply.yml@emarks/anyone-can-apply-with-approval
    with:
      tacos_gha_ref: refs/heads/emarks/anyone-can-apply-with-approval
