name: Terraform Apply

on:
  workflow_dispatch: null
  pull_request:
    types: [labeled] # need to filter for :tacos::apply label

jobs:
  tacos-gha:
    uses: getsentry/tacos-gha/.github/workflows/tacos_apply.yml@iw/force-unlock-happy
    with:
      tacos_gha_ref: refs/heads/iw/force-unlock-happy
